services:
  #Default
  api.controller.default:
    class: App\ApiBundle\Controller\DefaultController
    arguments: []
    public: true

  api.controller.phoneNumbers:
    class: App\ApiBundle\Controller\PhoneNumbersController
    arguments: ['@storage.model.phoneNumbers']
    public: true

  api.controller.countries:
      class: App\ApiBundle\Controller\HelperCountryController
      arguments: ['@storage.model.helperCountry']
      public: true