INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (17, 'BD', 'Bangladesh', '880');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (18, 'BE', 'Belgium', '32');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (19, 'BF', 'Burkina Faso', '226');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (20, 'BG', 'Bulgaria', '359');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (21, 'BA', 'Bosnia and Herzegovina', '387');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (22, 'BB', 'Barbados', '+1-246');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (23, 'WF', 'Wallis and Futuna', '681');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (24, 'BL', 'Saint Barthelemy', '590');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (25, 'BM', 'Bermuda', '+1-441');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (26, 'BN', 'Brunei', '673');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (27, 'BO', 'Bolivia', '591');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (28, 'BH', 'Bahrain', '973');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (29, 'BI', 'Burundi', '257');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (30, 'BJ', 'Benin', '229');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (31, 'BT', 'Bhutan', '975');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (32, 'JM', 'Jamaica', '+1-876');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (33, 'BV', 'Bouvet Island', null);
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (34, 'BW', 'Botswana', '267');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (35, 'WS', 'Samoa', '685');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (36, 'BQ', 'Bonaire', '599');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (37, 'BR', 'Brazil', '55');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (38, 'BS', 'Bahamas', '+1-242');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (39, 'JE', 'Jersey', '+44-1534');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (40, 'BY', 'Belarus', '375');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (41, 'BZ', 'Belize', '501');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (42, 'RU', 'Russia', '7');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (43, 'RW', 'Rwanda', '250');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (44, 'RS', 'Serbia', '381');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (45, 'TL', 'East Timor', '670');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (46, 'RE', 'Reunion', '262');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (47, 'TM', 'Turkmenistan', '993');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (48, 'TJ', 'Tajikistan', '992');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (49, 'RO', 'Romania', '40');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (50, 'TK', 'Tokelau', '690');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (51, 'GW', 'Guinea-Bissau', '245');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (52, 'GU', 'Guam', '+1-671');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (53, 'GT', 'Guatemala', '502');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (54, 'GS', 'South Georgia and the South Sandwich Islands', null);
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (55, 'GR', 'Greece', '30');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (56, 'GQ', 'Equatorial Guinea', '240');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (57, 'GP', 'Guadeloupe', '590');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (58, 'JP', 'Japan', '81');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (59, 'GY', 'Guyana', '592');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (60, 'GG', 'Guernsey', '+44-1481');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (61, 'GF', 'French Guiana', '594');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (62, 'GE', 'Georgia', '995');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (63, 'GD', 'Grenada', '+1-473');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (64, 'GB', 'United Kingdom', '44');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (65, 'GA', 'Gabon', '241');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (66, 'SV', 'El Salvador', '503');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (67, 'GN', 'Guinea', '224');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (68, 'GM', 'Gambia', '220');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (69, 'GL', 'Greenland', '299');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (70, 'GI', 'Gibraltar', '350');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (71, 'GH', 'Ghana', '233');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (72, 'OM', 'Oman', '968');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (73, 'TN', 'Tunisia', '216');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (74, 'JO', 'Jordan', '962');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (75, 'HR', 'Croatia', '385');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (76, 'HT', 'Haiti', '509');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (77, 'HU', 'Hungary', '36');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (78, 'HK', 'Hong Kong', '852');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (79, 'HN', 'Honduras', '504');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (80, 'HM', 'Heard Island and McDonald Islands', null);
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (81, 'VE', 'Venezuela', '58');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (82, 'PR', 'Puerto Rico', '+1-787');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (83, 'PS', 'Palestinian Territory', '970');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (84, 'PW', 'Palau', '680');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (85, 'PT', 'Portugal', '351');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (86, 'SJ', 'Svalbard and Jan Mayen', '47');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (87, 'PY', 'Paraguay', '595');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (88, 'IQ', 'Iraq', '964');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (89, 'PA', 'Panama', '507');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (90, 'PF', 'French Polynesia', '689');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (91, 'PG', 'Papua New Guinea', '675');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (92, 'PE', 'Peru', '51');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (93, 'PK', 'Pakistan', '92');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (94, 'PH', 'Philippines', '63');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (95, 'PN', 'Pitcairn', '870');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (96, 'PL', 'Poland', '48');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (97, 'PM', 'Saint Pierre and Miquelon', '508');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (98, 'ZM', 'Zambia', '260');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (99, 'EH', 'Western Sahara', '212');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (100, 'EE', 'Estonia', '372');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (101, 'EG', 'Egypt', null);
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (102, 'ZA', 'South Africa', '27');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (103, 'EC', 'Ecuador', '593');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (104, 'IT', 'Italy', '39');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (105, 'VN', 'Vietnam', '84');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (106, 'SB', 'Solomon Islands', '677');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (107, 'ET', 'Ethiopia', '251');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (108, 'SO', 'Somalia', '252');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (109, 'ZW', 'Zimbabwe', '263');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (110, 'SA', 'Saudi Arabia', '966');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (111, 'ES', 'Spain', '34');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (112, 'ER', 'Eritrea', '291');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (113, 'ME', 'Montenegro', '382');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (114, 'MD', 'Moldova', '373');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (115, 'MG', 'Madagascar', '261');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (116, 'MF', 'Saint Martin', '590');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (117, 'MA', 'Morocco', '212');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (118, 'MC', 'Monaco', '377');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (119, 'UZ', 'Uzbekistan', '998');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (120, 'MM', 'Myanmar', '95');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (121, 'ML', 'Mali', '223');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (122, 'MO', 'Macao', '853');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (123, 'MN', 'Mongolia', '976');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (124, 'MH', 'Marshall Islands', '692');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (125, 'MK', 'Macedonia', '389');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (126, 'MU', 'Mauritius', '230');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (127, 'MT', 'Malta', '356');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (128, 'MW', 'Malawi', '265');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (129, 'MV', 'Maldives', '960');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (130, 'MQ', 'Martinique', '596');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (131, 'MP', 'Northern Mariana Islands', '+1-670');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (132, 'MS', 'Montserrat', '+1-664');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (133, 'MR', 'Mauritania', '222');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (134, 'IM', 'Isle of Man', '+44-1624');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (135, 'UG', 'Uganda', '256');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (136, 'TZ', 'Tanzania', '255');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (137, 'MY', 'Malaysia', '60');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (138, 'MX', 'Mexico', '52');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (139, 'IL', 'Israel', '972');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (140, 'FR', 'France', '33');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (141, 'IO', 'British Indian Ocean Territory', '246');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (142, 'SH', 'Saint Helena', '290');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (143, 'FI', 'Finland', '358');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (144, 'FJ', 'Fiji', '679');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (145, 'FK', 'Falkland Islands', '500');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (146, 'FM', 'Micronesia', '691');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (147, 'FO', 'Faroe Islands', '298');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (148, 'NI', 'Nicaragua', '505');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (149, 'NL', 'Netherlands', '31');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (150, 'NO', 'Norway', '47');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (151, 'NA', 'Namibia', '264');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (152, 'VU', 'Vanuatu', '678');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (153, 'NC', 'New Caledonia', '687');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (154, 'NE', 'Niger', '227');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (155, 'NF', 'Norfolk Island', '672');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (156, 'NG', 'Nigeria', '234');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (157, 'NZ', 'New Zealand', '64');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (158, 'NP', 'Nepal', '977');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (159, 'NR', 'Nauru', '674');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (160, 'NU', 'Niue', '683');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (161, 'CK', 'Cook Islands', '682');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (162, 'XK', 'Kosovo', '');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (163, 'CI', 'Ivory Coast', '225');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (164, 'CH', 'Switzerland', '41');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (165, 'CO', 'Colombia', '57');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (166, 'CN', 'China', '86');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (167, 'CM', 'Cameroon', '237');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (168, 'CL', 'Chile', '56');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (169, 'CC', 'Cocos Islands', '61');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (170, 'CA', 'Canada', '1');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (171, 'CG', 'Republic of the Congo', '242');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (172, 'CF', 'Central African Republic', '236');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (173, 'CD', 'Democratic Republic of the Congo', '243');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (174, 'CZ', 'Czech Republic', '420');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (175, 'CY', 'Cyprus', '357');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (176, 'CX', 'Christmas Island', '61');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (177, 'CR', 'Costa Rica', '506');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (178, 'CW', 'Curacao', '599');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (179, 'CV', 'Cape Verde', '238');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (180, 'CU', 'Cuba', '53');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (181, 'SZ', 'Swaziland', '268');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (182, 'SY', 'Syria', '963');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (183, 'SX', 'Sint Maarten', '599');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (184, 'KG', 'Kyrgyzstan', '996');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (185, 'KE', 'Kenya', '254');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (186, 'SS', 'South Sudan', '211');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (187, 'SR', 'Suriname', '597');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (188, 'KI', 'Kiribati', '686');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (189, 'KH', 'KH', '855');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (190, 'KN', 'Saint Kitts and Nevis', '+1-869');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (191, 'KM', 'Comoros', '269');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (192, 'ST', 'Sao Tome and Principe', '239');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (193, 'SK', 'Slovakia', '421');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (194, 'KR', 'South Korea', '82');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (195, 'SI', 'Slovenia', '386');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (196, 'KP', 'North Korea', '850');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (197, 'KW', 'Kuwait', '965');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (198, 'SN', 'Senegal', '221');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (199, 'SM', 'San Marino', '378');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (200, 'SL', 'Sierra Leone', '232');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (201, 'SC', 'Seychelles', '248');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (202, 'KZ', 'Kazakhstan', '7');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (203, 'KY', 'Cayman Islands', '+1-345');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (204, 'SG', 'Singapore', '65');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (205, 'SE', 'Sweden', '46');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (206, 'SD', 'Sudan', '249');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (207, 'DO', 'Dominican Republic', '+1-809');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (208, 'DM', 'Dominica', '+1-767');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (209, 'DJ', 'Djibouti', '253');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (210, 'DK', 'Denmark', '45');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (211, 'VG', 'British Virgin Islands', '+1-284');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (212, 'DE', 'Germany', '49');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (213, 'YE', 'Yemen', '967');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (214, 'DZ', 'Algeria', '213');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (215, 'US', 'United States', '1');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (216, 'UY', 'Uruguay', '598');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (217, 'YT', 'Mayotte', '262');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (218, 'UM', 'United States Minor Outlying Islands', '1');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (219, 'LB', 'Lebanon', '961');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (220, 'LC', 'Saint Lucia', '+1-758');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (221, 'LA', 'Laos', '856');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (222, 'TV', 'Tuvalu', '688');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (223, 'TW', 'Taiwan', '886');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (224, 'TT', 'Trinidad and Tobago', '+1-868');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (225, 'TR', 'Turkey', '90');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (226, 'LK', 'Sri Lanka', '94');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (227, 'LI', 'Liechtenstein', '423');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (228, 'LV', 'Latvia', '371');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (229, 'TO', 'Tonga', '676');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (230, 'LT', 'Lithuania', '370');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (231, 'LU', 'Luxembourg', '352');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (232, 'LR', 'Liberia', '231');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (233, 'LS', 'Lesotho', '266');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (234, 'TH', 'Thailand', '66');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (235, 'TF', 'French Southern Territories', null);
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (236, 'TG', 'Togo', '228');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (237, 'TD', 'Chad', '235');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (238, 'TC', 'Turks and Caicos Islands', '+1-649');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (239, 'LY', 'Libya', '218');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (240, 'VA', 'Vatican', '379');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (241, 'VC', 'Saint Vincent and the Grenadines', '+1-784');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (242, 'AE', 'United Arab Emirates', '971');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (243, 'AD', 'Andorra', '376');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (244, 'AG', 'Antigua and Barbuda', '+1-268');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (245, 'AF', 'Afghanistan', '93');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (246, 'AI', 'Anguilla', '+1-264');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (247, 'VI', 'U.S. Virgin Islands', '+1-340');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (248, 'IS', 'Iceland', '354');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (249, 'IR', 'Iran', '98');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (250, 'AM', 'Armenia', '374');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (251, 'AL', 'Albania', '355');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (252, 'AO', 'Angola', '244');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (253, 'AQ', 'Antarctica', null);
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (254, 'AS', 'American Samoa', '+1-684');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (255, 'AR', 'Argentina', '54');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (256, 'AU', 'AU', '61');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (257, 'AT', 'Austria', '43');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (258, 'AW', 'Aruba', '297');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (259, 'IN', 'India', '91');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (260, 'AX', 'Aland Islands', '+358-18');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (261, 'AZ', 'Azerbaijan', '994');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (262, 'IE', 'Ireland', '353');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (263, 'ID', 'Indonesia', '62');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (264, 'UA', 'Ukraine', '380');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (265, 'QA', 'Qatar', '974');
INSERT INTO db_app.helper_country (id, country_code, country_name, country_phone_code) VALUES (266, 'MZ', 'Mozambique', '258');