App\StorageBundle\Entity\HelperCountry:
  type: entity
  table: helper_country
  repositoryClass: App\StorageBundle\Repository\HelperCountryRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    ## Mandatory Fields
    countryCode:
      type:   string
      length: 64
    countryName:
      type: string
      length: 64
    countryPhoneCode:
      type:   string
      length: 64
